# dmUser/helm/dmuser/Chart.yaml
apiVersion: v2
name: dmuser # 차트 이름
description: A Helm chart for the dmUser User Management API service (NestJS)
type: application
version: 0.1.0 # 차트 버전
appVersion: "1.0.0" # 애플리케이션 버전