# Development environment values
replicaCount: 1

image:
  repository: dmuser
  pullPolicy: IfNotPresent
  tag: ""

# 서비스 계정 설정 - 생성하지 않고 default 사용
serviceAccount:
  create: false
  name: "default"

service:
  type: ClusterIP
  port: 3001

# 기본 환경 변수만 유지
env:
  # 기본 환경 변수
  # 서버 설정
  - name: PORT
    value: 3001
  - name: NODE_ENV
    value: development

