apiVersion: v1
kind: Service
metadata:
  name: dmuser
  labels:
    {{- include "dmuser.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dmuser.selectorLabels" . | nindent 4 }}
