name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io                  # ➜ 레지스트리
  REPO_NAME: ${{ github.repository }} # ➜ prairiedoggg/dmRAG (대문자 포함)

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1) 빌드 변수 준비 ────────────────
      - name: Prepare vars (lower-case image name & version)
        id: prep
        run: |
          IMAGE_NAME_LC=$(echo "${REPO_NAME}" | tr '[:upper:]' '[:lower:]')
          VERSION=$(date +%Y%m%d%H%M%S)-${GITHUB_SHA::7}
          echo "IMAGE=${REGISTRY}/${IMAGE_NAME_LC}" >> $GITHUB_ENV
          echo "VERSION=${VERSION}"               >> $GITHUB_ENV
      # 2) 레지스트리 로그인 ───────────────
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}   # 조직 토큰이면 PAT 사용

      # 3) Docker Build & Push ───────────
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}:${{ env.VERSION }}

      # 4) Helm values.yaml 업데이트 ──────
      - name: Update Helm values (image repo & tag → 소문자)
        run: |
          # image.repository ↘︎ ghcr.io/prairiedoggg/dmuser
          # image.tag         ↘︎ 20250514073232-8179f5c
          yq -i \
            '.image.repository = strenv(IMAGE) |
             .image.tag        = strenv(VERSION)' \
            $(grep -rl '^image:' helm)
      # 5) 변경사항 커밋 & 푸시 ───────────
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: 'helm/dmuser/values.yaml'
          commit_message: "ci: image → ${IMAGE}:${VERSION}"
          push_options: '--force-with-lease'
